"""add followers

Revision ID: 78554b0d5a81
Revises: afbd2637cf61
Create Date: 2022-04-07 23:59:13.105454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78554b0d5a81'
down_revision = 'afbd2637cf61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follower',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follower')
    # ### end Alembic commands ###
